name: New VM

on:
  workflow_dispatch:

env:
  SSH_KEY: cache/sshkey
  INSTANCE_NAME: first-instance

jobs:
  new-vm:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      # - name: Restore cache
      #   uses: actions/cache/restore@v3
      #   with:
      #     path: cache
      #     key: new-vm-cache

      - name: Download Yandex Cloud CLI
        run: curl https://raw.githubusercontent.com/Jokero/yandex-cloud-cli-install-for-ci/master/install.sh | bash
      
      - name: Check version
        run: ~/yandex-cloud/bin/yc -v

      - name: Show existing compute instances
        run: ~/yandex-cloud/bin/yc --token ${{ secrets.YC_TOKEN }} --cloud-id ${{ secrets.YC_CLOUD_ID }} --folder-id ${{ secrets.YC_FOLDER_ID }} compute instance list

      - name: Create cache dir
        run: mkdir -p cache

      - name: Generate new key pair if not exist
        run: "[ -f $SSH_KEY ] || ssh-keygen -b 2048 -t rsa -f $SSH_KEY -q -N \"\""

      - name: Create Yandex.Cloud compute instance
        run: |
          ~/yandex-cloud/bin/yc \
            --token ${{ secrets.YC_TOKEN }} --cloud-id ${{ secrets.YC_CLOUD_ID }} --folder-id ${{ secrets.YC_FOLDER_ID }} \
            compute instance create \
            --name $INSTANCE_NAME \
            --zone ru-central1-a \
            --public-ip \
            --create-boot-disk size=30G,image-folder-id=standard-images,image-family=centos-stream-8 \
            --preemptible \
            --core-fraction 50 \
            --memory 8 \
            --ssh-key $SSH_KEY.pub
      
      - name: Show existing compute instances again
        run: ~/yandex-cloud/bin/yc --token ${{ secrets.YC_TOKEN }} --cloud-id ${{ secrets.YC_CLOUD_ID }} --folder-id ${{ secrets.YC_FOLDER_ID }} compute instance list
      
      - name: Print new vm config to file
        run: |
          ~/yandex-cloud/bin/yc \
            --token ${{ secrets.YC_TOKEN }} --cloud-id ${{ secrets.YC_CLOUD_ID }} --folder-id ${{ secrets.YC_FOLDER_ID }} \
            compute instance get $INSTANCE_NAME > cache/vmconfig.txt
        
      - name: Save address to cache
        run: "cat cache/vmconfig.txt | grep -v 'address: 10'  | grep ' address:' | tr -d ' address:' > cache/addr"
      
      # - name: Save cache
      #   uses: actions/cache/save@v3
      #   with:
      #     path: cache
      #     key: new-vm-cache
      
      - name: Upload cache to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: new-vm-cache
          path: cache
          retention-days: 1

  configure-vm:
    runs-on: ubuntu-latest
    needs: [ new-vm ]

    steps:
      - uses: actions/checkout@v3

      - name: Download cache from artifacts
        uses: actions/download-artifact@v3
        with:
          name: new-vm-cache
          path: cache

      - run: uname -a
      - run: eval $(ssh-agent -s)
      - run: 'command -v ssh-agent >/dev/null || ( apt-get update -y && apt-get install openssh-client -y )'
      # - run: cat $SSH_KEY | tr -d '\r' | ssh-add -
      # - run: mkdir -p ~/.ssh
      # - run: chmod 700 ~/.ssh
      # - run: '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" >> ~/.ssh/config'
      
      - run: cat cache/addr >> "$REMOTE_ADDR"

      - name: copy file via scp
        uses: appleboy/scp-action@v0.1.4
        with:
          host: $REMOTE_ADDR
          username: yc-user
          source: tomcat.service
          target: tomcat.service
          key_path: $SSH_KEY

      # - name: executing remote ssh commands using password
      #   uses: appleboy/ssh-action@v1.0.0
      #   with:
      #     host: $REMOTE_ADDR
      #     script: whoami
      
      - run: "scp -i $SSH_KEY.pub -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null tomcat.service yc-user@`cat cache/addr`:"
      - run: "scp -i $SSH_KEY.pub -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null context.xml yc-user@`cat cache/addr`:"
      - run: "scp -i $SSH_KEY.pub -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null pg_hba.conf yc-user@`cat cache/addr`:"
      - run: echo ./dl-cloud-mail-ru.sh $LINK_PG postgresql-42.0.0.jar > download.sh
      - run: echo ./dl-cloud-mail-ru.sh $LINK_HELP prhelp.war >> download.sh
      - run: echo ./dl-cloud-mail-ru.sh $LINK_WEB prweb.war >> download.sh
      - run: echo ./dl-cloud-mail-ru.sh $LINK_DUMP1 pega.001 >> download.sh
      - run: echo ./dl-cloud-mail-ru.sh $LINK_DUMP2 pega.002 >> download.sh
      - run: echo ./dl-cloud-mail-ru.sh $LINK_DUMP3 pega.crc >> download.sh
      - run: echo exit >> download.sh
      - run: ssh -i $SSH_KEY.pub -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t -t yc-user@`cat cache/addr` < before.sh
      - run: ssh -i $SSH_KEY.pub -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t -t yc-user@`cat cache/addr` < download.sh
      - run: ssh -i $SSH_KEY.pub -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t -t yc-user@`cat cache/addr` < db-install.sh
      - run: ssh -i $SSH_KEY.pub -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -t -t yc-user@`cat cache/addr` < tomcat-install.sh
