name: New VM

on:
  workflow_dispatch:

env:
  SSH_KEY: cache/sshkey

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache/restore@v3
        with:
          path: cache
          key: new-vm-cache

      - name: Download Yandex Cloud CLI
        run: |
          curl https://raw.githubusercontent.com/Jokero/yandex-cloud-cli-install-for-ci/master/install.sh | bash
          source "/home/runner/.bashrc"
      
      - name: Check version
        run: ~/yandex-cloud/bin/yc -v

      - name: Show existing compute instances
        run: ~/yandex-cloud/bin/yc --token ${{ secrets.YC_TOKEN }} --cloud-id ${{ secrets.YC_CLOUD_ID }} --folder-id ${{ secrets.YC_FOLDER_ID }} compute instance list

      - name: Create cache dir
        run: mkdir -p cache

      - name: Generate new key pair if not exist
        run: "[ -f $SSH_KEY ] || ssh-keygen -b 2048 -t rsa -f $SSH_KEY -q -N \"\""

      - name: Create Yandex.Cloud compute instance
        run: |
          ~/yandex-cloud/bin/yc \
            --token ${{ secrets.YC_TOKEN }} --cloud-id ${{ secrets.YC_CLOUD_ID }} --folder-id ${{ secrets.YC_FOLDER_ID }} \
            compute instance create \
            --name first-instance \
            --zone ru-central1-a \
            --public-ip \
            --create-boot-disk size=30G,image-folder-id=standard-images,image-family=centos-stream-8 \
            --preemptible \
            --core-fraction 50 \
            --memory 8 \
            --ssh-key $SSH_KEY.pub
      
      - name: Show existing compute instances again
        run: ~/yandex-cloud/bin/yc --token ${{ secrets.YC_TOKEN }} --cloud-id ${{ secrets.YC_CLOUD_ID }} --folder-id ${{ secrets.YC_FOLDER_ID }} compute instance list
      
      - name: Print new vm config to file
        run: |
          ~/yandex-cloud/bin/yc \
            --token ${{ secrets.YC_TOKEN }} --cloud-id ${{ secrets.YC_CLOUD_ID }} --folder-id ${{ secrets.YC_FOLDER_ID }} \
            compute instance get first-instance > cache/vmconfig.txt
        
      - name: Save address to cache
        run: "cat cache/vmconfig.txt | grep -v 'address: 10'  | grep ' address:' | tr -d ' address:' > cache/addr"
      
      - name: Save cache
        uses: actions/cache/save@v3
        with:
          path: cache
          key: new-vm-cache
      
      - name: Upload cache to artifacts
        uses: actions/upload-artifact@v3
        with:
          name: new-vm-cache
          path: cache
          retention-days: 1